use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Move {
    // Normal Type
    Pound,
    Doubleslap,
    PayDay,
    Scratch,
    Guillotine,
    SwordsDance,
    Cut,
    Bind,
    Slam,
    Stomp,
    Headbutt,
    HornAttack,
    FuryAttack,
    HornDrill,
    Tackle,
    BodySlam,
    Wrap,
    Harden,
    TakeDown,
    Thrash,
    DoubleEdge,
    TailWhip,
    Leer,
    Bite,
    Growl,
    Roar,
    Sing,
    Supersonic,
    SonicBoom,
    Disable,
    Agility,
    QuickAttack,
    Rage,
    Mimic,
    Screech,
    DoubleTeam,
    Recover,
    Minimize,
    Withdraw,
    DefenseCurl,
    Barrier,
    FocusEnergy,
    Bide,
    Metronome,
    MirrorMove,
    SelfDestruct,
    Clamp,
    Swift,
    SpikeCannon,
    Constrict,
    SoftBoiled,
    Glare,
    Transform,
    Explosion,
    FurySwipes,
    Rest,
    HyperFang,
    Sharpen,
    Conversion,
    TriAttack,
    SuperFang,
    Slash,
    Substitute,
    HyperBeam,

    // Fighting Type
    KarateChop,
    CometPunch,
    MegaPunch,
    KOPunch,
    DoubleKick,
    MegaKick,
    JumpKick,
    RollingKick,
    Submission,
    LowKick,
    Counter,
    SeismicToss,
    Strength,
    Meditate,
    HighJumpKick,
    Barrage,
    DizzyPunch,

    // Flying Type
    RazorWind,
    Gust,
    WingAttack,
    Whirlwind,
    Fly,
    Peck,
    DrillPeck,
    SkyAttack,

    // Rock Type
    ViceGrip,
    RockThrow,
    SkullBash,
    RockSlide,
    AncientPower,

    // Ground Type
    SandAttack,
    Earthquake,
    Fissure,
    Dig,
    BoneClub,
    Bonemerang,

    // Poison Type
    PoisonSting,
    Twineedle,
    Acid,
    Toxic,
    Haze,
    Smog,
    Sludge,
    PoisonJab,
    PoisonGas,
    AcidArmor,

    // Bug Type
    PinMissile,
    SilverWind,
    StringShot,
    LeechLife,

    // Fire Type
    FirePunch,
    BlazeKick,
    FireFang,
    Ember,
    Flamethrower,
    WillOWisp,
    FireSpin,
    Smokescreen,
    FireBlast,

    // Water Type
    Mist,
    WaterGun,
    HydroPump,
    Surf,
    Bubblebeam,
    Waterfall,
    Bubble,
    Splash,
    Bubblehammer,

    // Grass Type
    VineWhip,
    Absorb,
    MegaDrain,
    GigaDrain,
    LeechSeed,
    Growth,
    RazorLeaf,
    SolarBeam,
    PoisonPowder,
    StunSpore,
    SleepPowder,
    PetalDance,
    Spore,
    EggBomb,

    // Ice Type
    IcePunch,
    IceBeam,
    Blizzard,
    AuroraBeam,

    // Electric Type
    ThunderPunch,
    Shock,
    Discharge,
    ThunderWave,
    Thunderclap,
    ChargeBeam,
    Lightning,
    Flash,

    // Psychic Type
    Confusion,
    Psybeam,
    Perplex,
    Hypnosis,
    Teleport,
    ConfuseRay,
    LightScreen,
    Reflect,
    Amnesia,
    Kinesis,
    Psywave,
    DreamEater,
    LovelyKiss,

    // Ghost Type
    NightShade,
    Lick,
    ShadowBall,

    // Dragon Type
    Outrage,
    DragonRage,

    // Typeless
    Struggle,
    HittingItself,
}

impl std::str::FromStr for Move {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let normalized = s.to_uppercase().replace([' ', '-', '_'], "");

        match normalized.as_str() {
            "POUND" => Ok(Move::Pound),
            "DOUBLESLAP" => Ok(Move::Doubleslap),
            "PAYDAY" => Ok(Move::PayDay),
            "SCRATCH" => Ok(Move::Scratch),
            "GUILLOTINE" => Ok(Move::Guillotine),
            "SWORDSDANCE" => Ok(Move::SwordsDance),
            "CUT" => Ok(Move::Cut),
            "BIND" => Ok(Move::Bind),
            "SLAM" => Ok(Move::Slam),
            "STOMP" => Ok(Move::Stomp),
            "HEADBUTT" => Ok(Move::Headbutt),
            "HORNATTACK" => Ok(Move::HornAttack),
            "FURYATTACK" => Ok(Move::FuryAttack),
            "HORNDRILL" => Ok(Move::HornDrill),
            "TACKLE" => Ok(Move::Tackle),
            "BODYSLAM" => Ok(Move::BodySlam),
            "WRAP" => Ok(Move::Wrap),
            "HARDEN" => Ok(Move::Harden),
            "TAKEDOWN" => Ok(Move::TakeDown),
            "THRASH" => Ok(Move::Thrash),
            "DOUBLEEDGE" => Ok(Move::DoubleEdge),
            "TAILWHIP" => Ok(Move::TailWhip),
            "LEER" => Ok(Move::Leer),
            "BITE" => Ok(Move::Bite),
            "GROWL" => Ok(Move::Growl),
            "ROAR" => Ok(Move::Roar),
            "SING" => Ok(Move::Sing),
            "SUPERSONIC" => Ok(Move::Supersonic),
            "SONICBOOM" => Ok(Move::SonicBoom),
            "DISABLE" => Ok(Move::Disable),
            "AGILITY" => Ok(Move::Agility),
            "QUICKATTACK" => Ok(Move::QuickAttack),
            "RAGE" => Ok(Move::Rage),
            "MIMIC" => Ok(Move::Mimic),
            "SCREECH" => Ok(Move::Screech),
            "DOUBLETEAM" => Ok(Move::DoubleTeam),
            "RECOVER" => Ok(Move::Recover),
            "MINIMIZE" => Ok(Move::Minimize),
            "WITHDRAW" => Ok(Move::Withdraw),
            "DEFENSECURL" => Ok(Move::DefenseCurl),
            "BARRIER" => Ok(Move::Barrier),
            "FOCUSENERGY" => Ok(Move::FocusEnergy),
            "BIDE" => Ok(Move::Bide),
            "METRONOME" => Ok(Move::Metronome),
            "MIRRORMOVE" => Ok(Move::MirrorMove),
            "SELFDESTRUCT" => Ok(Move::SelfDestruct),
            "CLAMP" => Ok(Move::Clamp),
            "SWIFT" => Ok(Move::Swift),
            "SPIKECANNON" => Ok(Move::SpikeCannon),
            "CONSTRICT" => Ok(Move::Constrict),
            "SOFTBOILED" => Ok(Move::SoftBoiled),
            "GLARE" => Ok(Move::Glare),
            "TRANSFORM" => Ok(Move::Transform),
            "EXPLOSION" => Ok(Move::Explosion),
            "FURYSWIPES" => Ok(Move::FurySwipes),
            "REST" => Ok(Move::Rest),
            "HYPERFANG" => Ok(Move::HyperFang),
            "SHARPEN" => Ok(Move::Sharpen),
            "CONVERSION" => Ok(Move::Conversion),
            "TRIATTACK" => Ok(Move::TriAttack),
            "SUPERFANG" => Ok(Move::SuperFang),
            "SLASH" => Ok(Move::Slash),
            "SUBSTITUTE" => Ok(Move::Substitute),
            "HYPERBEAM" => Ok(Move::HyperBeam),
            "KARATECHOP" => Ok(Move::KarateChop),
            "COMETPUNCH" => Ok(Move::CometPunch),
            "MEGAPUNCH" => Ok(Move::MegaPunch),
            "KOPUNCH" => Ok(Move::KOPunch),
            "DOUBLEKICK" => Ok(Move::DoubleKick),
            "MEGAKICK" => Ok(Move::MegaKick),
            "JUMPKICK" => Ok(Move::JumpKick),
            "ROLLINGKICK" => Ok(Move::RollingKick),
            "SUBMISSION" => Ok(Move::Submission),
            "LOWKICK" => Ok(Move::LowKick),
            "COUNTER" => Ok(Move::Counter),
            "SEISMICTOSS" => Ok(Move::SeismicToss),
            "STRENGTH" => Ok(Move::Strength),
            "MEDITATE" => Ok(Move::Meditate),
            "HIGHJUMPKICK" => Ok(Move::HighJumpKick),
            "BARRAGE" => Ok(Move::Barrage),
            "DIZZYPUNCH" => Ok(Move::DizzyPunch),
            "RAZORWIND" => Ok(Move::RazorWind),
            "GUST" => Ok(Move::Gust),
            "WINGATTACK" => Ok(Move::WingAttack),
            "WHIRLWIND" => Ok(Move::Whirlwind),
            "FLY" => Ok(Move::Fly),
            "PECK" => Ok(Move::Peck),
            "DRILLPECK" => Ok(Move::DrillPeck),
            "SKYATTACK" => Ok(Move::SkyAttack),
            "VICEGRIP" => Ok(Move::ViceGrip),
            "ROCKTHROW" => Ok(Move::RockThrow),
            "SKULLBASH" => Ok(Move::SkullBash),
            "ROCKSLIDE" => Ok(Move::RockSlide),
            "ANCIENTPOWER" => Ok(Move::AncientPower),
            "SANDATTACK" => Ok(Move::SandAttack),
            "EARTHQUAKE" => Ok(Move::Earthquake),
            "FISSURE" => Ok(Move::Fissure),
            "DIG" => Ok(Move::Dig),
            "BONECLUB" => Ok(Move::BoneClub),
            "BONEMERANG" => Ok(Move::Bonemerang),
            "POISONSTING" => Ok(Move::PoisonSting),
            "TWINEEDLE" => Ok(Move::Twineedle),
            "ACID" => Ok(Move::Acid),
            "TOXIC" => Ok(Move::Toxic),
            "HAZE" => Ok(Move::Haze),
            "SMOG" => Ok(Move::Smog),
            "SLUDGE" => Ok(Move::Sludge),
            "POISONJAB" => Ok(Move::PoisonJab),
            "POISONGAS" => Ok(Move::PoisonGas),
            "ACIDARMOR" => Ok(Move::AcidArmor),
            "PINMISSILE" => Ok(Move::PinMissile),
            "SILVERWIND" => Ok(Move::SilverWind),
            "STRINGSHOT" => Ok(Move::StringShot),
            "LEECHLIFE" => Ok(Move::LeechLife),
            "FIREPUNCH" => Ok(Move::FirePunch),
            "BLAZEKICK" => Ok(Move::BlazeKick),
            "FIREFANG" => Ok(Move::FireFang),
            "EMBER" => Ok(Move::Ember),
            "FLAMETHROWER" => Ok(Move::Flamethrower),
            "WILLOWISP" => Ok(Move::WillOWisp),
            "FIRESPIN" => Ok(Move::FireSpin),
            "SMOKESCREEN" => Ok(Move::Smokescreen),
            "FIREBLAST" => Ok(Move::FireBlast),
            "MIST" => Ok(Move::Mist),
            "WATERGUN" => Ok(Move::WaterGun),
            "HYDROPUMP" => Ok(Move::HydroPump),
            "SURF" => Ok(Move::Surf),
            "BUBBLEBEAM" => Ok(Move::Bubblebeam),
            "WATERFALL" => Ok(Move::Waterfall),
            "BUBBLE" => Ok(Move::Bubble),
            "SPLASH" => Ok(Move::Splash),
            "BUBBLEHAMMER" => Ok(Move::Bubblehammer),
            "VINEWHIP" => Ok(Move::VineWhip),
            "ABSORB" => Ok(Move::Absorb),
            "MEGADRAIN" => Ok(Move::MegaDrain),
            "GIGADRAIN" => Ok(Move::GigaDrain),
            "LEECHSEED" => Ok(Move::LeechSeed),
            "GROWTH" => Ok(Move::Growth),
            "RAZORLEAF" => Ok(Move::RazorLeaf),
            "SOLARBEAM" => Ok(Move::SolarBeam),
            "POISONPOWDER" => Ok(Move::PoisonPowder),
            "STUNSPORE" => Ok(Move::StunSpore),
            "SLEEPPOWDER" => Ok(Move::SleepPowder),
            "PETALDANCE" => Ok(Move::PetalDance),
            "SPORE" => Ok(Move::Spore),
            "EGGBOMB" => Ok(Move::EggBomb),
            "ICEPUNCH" => Ok(Move::IcePunch),
            "ICEBEAM" => Ok(Move::IceBeam),
            "BLIZZARD" => Ok(Move::Blizzard),
            "AURORABEAM" => Ok(Move::AuroraBeam),
            "THUNDERPUNCH" => Ok(Move::ThunderPunch),
            "SHOCK" => Ok(Move::Shock),
            "DISCHARGE" => Ok(Move::Discharge),
            "THUNDERWAVE" => Ok(Move::ThunderWave),
            "THUNDERCLAP" => Ok(Move::Thunderclap),
            "CHARGEBEAM" => Ok(Move::ChargeBeam),
            "LIGHTNING" => Ok(Move::Lightning),
            "FLASH" => Ok(Move::Flash),
            "CONFUSION" => Ok(Move::Confusion),
            "PSYBEAM" => Ok(Move::Psybeam),
            "PERPLEX" => Ok(Move::Perplex),
            "HYPNOSIS" => Ok(Move::Hypnosis),
            "TELEPORT" => Ok(Move::Teleport),
            "CONFUSERAY" => Ok(Move::ConfuseRay),
            "LIGHTSCREEN" => Ok(Move::LightScreen),
            "REFLECT" => Ok(Move::Reflect),
            "AMNESIA" => Ok(Move::Amnesia),
            "KINESIS" => Ok(Move::Kinesis),
            "PSYWAVE" => Ok(Move::Psywave),
            "DREAMEATER" => Ok(Move::DreamEater),
            "LOVELYKISS" => Ok(Move::LovelyKiss),
            "NIGHTSHADE" => Ok(Move::NightShade),
            "LICK" => Ok(Move::Lick),
            "SHADOWBALL" => Ok(Move::ShadowBall),
            "OUTRAGE" => Ok(Move::Outrage),
            "DRAGONRAGE" => Ok(Move::DragonRage),
            "STRUGGLE" => Ok(Move::Struggle),
            "HITITSELF" => Ok(Move::HittingItself),
            _ => Err(format!("Unknown move: {}", s)),
        }
    }
}
