use serde::{Deserialize, Serialize};
use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Species {
    // Gen 1 - Kanto (001-151)
    Bulbasaur,     // 001
    Ivysaur,       // 002
    Venusaur,      // 003
    Charmander,    // 004
    Charmeleon,    // 005
    Charizard,     // 006
    Squirtle,      // 007
    Wartortle,     // 008
    Blastoise,     // 009
    Caterpie,      // 010
    Metapod,       // 011
    Butterfree,    // 012
    Weedle,        // 013
    Kakuna,        // 014
    Beedrill,      // 015
    Pidgey,        // 016
    Pidgeotto,     // 017
    Pidgeot,       // 018
    Rattata,       // 019
    Raticate,      // 020
    Spearow,       // 021
    Fearow,        // 022
    Ekans,         // 023
    Arbok,         // 024
    Pikachu,       // 025
    Raichu,        // 026
    Sandshrew,     // 027
    Sandslash,     // 028
    NidoranFemale, // 029
    Nidorina,      // 030
    Nidoqueen,     // 031
    NidoranMale,   // 032
    Nidorino,      // 033
    Nidoking,      // 034
    Clefairy,      // 035
    Clefable,      // 036
    Vulpix,        // 037
    Ninetales,     // 038
    Jigglypuff,    // 039
    Wigglytuff,    // 040
    Zubat,         // 041
    Golbat,        // 042
    Oddish,        // 043
    Gloom,         // 044
    Vileplume,     // 045
    Paras,         // 046
    Parasect,      // 047
    Venonat,       // 048
    Venomoth,      // 049
    Diglett,       // 050
    Dugtrio,       // 051
    Meowth,        // 052
    Persian,       // 053
    Psyduck,       // 054
    Golduck,       // 055
    Mankey,        // 056
    Primeape,      // 057
    Growlithe,     // 058
    Arcanine,      // 059
    Poliwag,       // 060
    Poliwhirl,     // 061
    Poliwrath,     // 062
    Abra,          // 063
    Kadabra,       // 064
    Alakazam,      // 065
    Machop,        // 066
    Machoke,       // 067
    Machamp,       // 068
    Bellsprout,    // 069
    Weepinbell,    // 070
    Victreebel,    // 071
    Tentacool,     // 072
    Tentacruel,    // 073
    Geodude,       // 074
    Graveler,      // 075
    Golem,         // 076
    Ponyta,        // 077
    Rapidash,      // 078
    Slowpoke,      // 079
    Slowbro,       // 080
    Magnemite,     // 081
    Magneton,      // 082
    Farfetchd,     // 083
    Doduo,         // 084
    Dodrio,        // 085
    Seel,          // 086
    Dewgong,       // 087
    Grimer,        // 088
    Muk,           // 089
    Shellder,      // 090
    Cloyster,      // 091
    Gastly,        // 092
    Haunter,       // 093
    Gengar,        // 094
    Onix,          // 095
    Drowzee,       // 096
    Hypno,         // 097
    Krabby,        // 098
    Kingler,       // 099
    Voltorb,       // 100
    Electrode,     // 101
    Exeggcute,     // 102
    Exeggutor,     // 103
    Cubone,        // 104
    Marowak,       // 105
    Hitmonlee,     // 106
    Hitmonchan,    // 107
    Lickitung,     // 108
    Koffing,       // 109
    Weezing,       // 110
    Rhyhorn,       // 111
    Rhydon,        // 112
    Chansey,       // 113
    Tangela,       // 114
    Kangaskhan,    // 115
    Horsea,        // 116
    Seadra,        // 117
    Goldeen,       // 118
    Seaking,       // 119
    Staryu,        // 120
    Starmie,       // 121
    MrMime,        // 122
    Scyther,       // 123
    Jynx,          // 124
    Electabuzz,    // 125
    Magmar,        // 126
    Pinsir,        // 127
    Tauros,        // 128
    Magikarp,      // 129
    Gyarados,      // 130
    Lapras,        // 131
    Ditto,         // 132
    Eevee,         // 133
    Vaporeon,      // 134
    Jolteon,       // 135
    Flareon,       // 136
    Porygon,       // 137
    Omanyte,       // 138
    Omastar,       // 139
    Kabuto,        // 140
    Kabutops,      // 141
    Aerodactyl,    // 142
    Snorlax,       // 143
    Articuno,      // 144
    Zapdos,        // 145
    Moltres,       // 146
    Dratini,       // 147
    Dragonair,     // 148
    Dragonite,     // 149
    Mewtwo,        // 150
    Mew,           // 151
}

impl Species {
    /// Get the Pokedex number for this species
    pub fn pokedex_number(self) -> u16 {
        match self {
            Species::Bulbasaur => 1,
            Species::Ivysaur => 2,
            Species::Venusaur => 3,
            Species::Charmander => 4,
            Species::Charmeleon => 5,
            Species::Charizard => 6,
            Species::Squirtle => 7,
            Species::Wartortle => 8,
            Species::Blastoise => 9,
            Species::Caterpie => 10,
            Species::Metapod => 11,
            Species::Butterfree => 12,
            Species::Weedle => 13,
            Species::Kakuna => 14,
            Species::Beedrill => 15,
            Species::Pidgey => 16,
            Species::Pidgeotto => 17,
            Species::Pidgeot => 18,
            Species::Rattata => 19,
            Species::Raticate => 20,
            Species::Spearow => 21,
            Species::Fearow => 22,
            Species::Ekans => 23,
            Species::Arbok => 24,
            Species::Pikachu => 25,
            Species::Raichu => 26,
            Species::Sandshrew => 27,
            Species::Sandslash => 28,
            Species::NidoranFemale => 29,
            Species::Nidorina => 30,
            Species::Nidoqueen => 31,
            Species::NidoranMale => 32,
            Species::Nidorino => 33,
            Species::Nidoking => 34,
            Species::Clefairy => 35,
            Species::Clefable => 36,
            Species::Vulpix => 37,
            Species::Ninetales => 38,
            Species::Jigglypuff => 39,
            Species::Wigglytuff => 40,
            Species::Zubat => 41,
            Species::Golbat => 42,
            Species::Oddish => 43,
            Species::Gloom => 44,
            Species::Vileplume => 45,
            Species::Paras => 46,
            Species::Parasect => 47,
            Species::Venonat => 48,
            Species::Venomoth => 49,
            Species::Diglett => 50,
            Species::Dugtrio => 51,
            Species::Meowth => 52,
            Species::Persian => 53,
            Species::Psyduck => 54,
            Species::Golduck => 55,
            Species::Mankey => 56,
            Species::Primeape => 57,
            Species::Growlithe => 58,
            Species::Arcanine => 59,
            Species::Poliwag => 60,
            Species::Poliwhirl => 61,
            Species::Poliwrath => 62,
            Species::Abra => 63,
            Species::Kadabra => 64,
            Species::Alakazam => 65,
            Species::Machop => 66,
            Species::Machoke => 67,
            Species::Machamp => 68,
            Species::Bellsprout => 69,
            Species::Weepinbell => 70,
            Species::Victreebel => 71,
            Species::Tentacool => 72,
            Species::Tentacruel => 73,
            Species::Geodude => 74,
            Species::Graveler => 75,
            Species::Golem => 76,
            Species::Ponyta => 77,
            Species::Rapidash => 78,
            Species::Slowpoke => 79,
            Species::Slowbro => 80,
            Species::Magnemite => 81,
            Species::Magneton => 82,
            Species::Farfetchd => 83,
            Species::Doduo => 84,
            Species::Dodrio => 85,
            Species::Seel => 86,
            Species::Dewgong => 87,
            Species::Grimer => 88,
            Species::Muk => 89,
            Species::Shellder => 90,
            Species::Cloyster => 91,
            Species::Gastly => 92,
            Species::Haunter => 93,
            Species::Gengar => 94,
            Species::Onix => 95,
            Species::Drowzee => 96,
            Species::Hypno => 97,
            Species::Krabby => 98,
            Species::Kingler => 99,
            Species::Voltorb => 100,
            Species::Electrode => 101,
            Species::Exeggcute => 102,
            Species::Exeggutor => 103,
            Species::Cubone => 104,
            Species::Marowak => 105,
            Species::Hitmonlee => 106,
            Species::Hitmonchan => 107,
            Species::Lickitung => 108,
            Species::Koffing => 109,
            Species::Weezing => 110,
            Species::Rhyhorn => 111,
            Species::Rhydon => 112,
            Species::Chansey => 113,
            Species::Tangela => 114,
            Species::Kangaskhan => 115,
            Species::Horsea => 116,
            Species::Seadra => 117,
            Species::Goldeen => 118,
            Species::Seaking => 119,
            Species::Staryu => 120,
            Species::Starmie => 121,
            Species::MrMime => 122,
            Species::Scyther => 123,
            Species::Jynx => 124,
            Species::Electabuzz => 125,
            Species::Magmar => 126,
            Species::Pinsir => 127,
            Species::Tauros => 128,
            Species::Magikarp => 129,
            Species::Gyarados => 130,
            Species::Lapras => 131,
            Species::Ditto => 132,
            Species::Eevee => 133,
            Species::Vaporeon => 134,
            Species::Jolteon => 135,
            Species::Flareon => 136,
            Species::Porygon => 137,
            Species::Omanyte => 138,
            Species::Omastar => 139,
            Species::Kabuto => 140,
            Species::Kabutops => 141,
            Species::Aerodactyl => 142,
            Species::Snorlax => 143,
            Species::Articuno => 144,
            Species::Zapdos => 145,
            Species::Moltres => 146,
            Species::Dratini => 147,
            Species::Dragonair => 148,
            Species::Dragonite => 149,
            Species::Mewtwo => 150,
            Species::Mew => 151,
        }
    }

    /// Get the display name for this species
    pub fn name(self) -> &'static str {
        match self {
            Species::Bulbasaur => "Bulbasaur",
            Species::Ivysaur => "Ivysaur",
            Species::Venusaur => "Venusaur",
            Species::Charmander => "Charmander",
            Species::Charmeleon => "Charmeleon",
            Species::Charizard => "Charizard",
            Species::Squirtle => "Squirtle",
            Species::Wartortle => "Wartortle",
            Species::Blastoise => "Blastoise",
            Species::Caterpie => "Caterpie",
            Species::Metapod => "Metapod",
            Species::Butterfree => "Butterfree",
            Species::Weedle => "Weedle",
            Species::Kakuna => "Kakuna",
            Species::Beedrill => "Beedrill",
            Species::Pidgey => "Pidgey",
            Species::Pidgeotto => "Pidgeotto",
            Species::Pidgeot => "Pidgeot",
            Species::Rattata => "Rattata",
            Species::Raticate => "Raticate",
            Species::Spearow => "Spearow",
            Species::Fearow => "Fearow",
            Species::Ekans => "Ekans",
            Species::Arbok => "Arbok",
            Species::Pikachu => "Pikachu",
            Species::Raichu => "Raichu",
            Species::Sandshrew => "Sandshrew",
            Species::Sandslash => "Sandslash",
            Species::NidoranFemale => "Nidoran♀",
            Species::Nidorina => "Nidorina",
            Species::Nidoqueen => "Nidoqueen",
            Species::NidoranMale => "Nidoran♂",
            Species::Nidorino => "Nidorino",
            Species::Nidoking => "Nidoking",
            Species::Clefairy => "Clefairy",
            Species::Clefable => "Clefable",
            Species::Vulpix => "Vulpix",
            Species::Ninetales => "Ninetales",
            Species::Jigglypuff => "Jigglypuff",
            Species::Wigglytuff => "Wigglytuff",
            Species::Zubat => "Zubat",
            Species::Golbat => "Golbat",
            Species::Oddish => "Oddish",
            Species::Gloom => "Gloom",
            Species::Vileplume => "Vileplume",
            Species::Paras => "Paras",
            Species::Parasect => "Parasect",
            Species::Venonat => "Venonat",
            Species::Venomoth => "Venomoth",
            Species::Diglett => "Diglett",
            Species::Dugtrio => "Dugtrio",
            Species::Meowth => "Meowth",
            Species::Persian => "Persian",
            Species::Psyduck => "Psyduck",
            Species::Golduck => "Golduck",
            Species::Mankey => "Mankey",
            Species::Primeape => "Primeape",
            Species::Growlithe => "Growlithe",
            Species::Arcanine => "Arcanine",
            Species::Poliwag => "Poliwag",
            Species::Poliwhirl => "Poliwhirl",
            Species::Poliwrath => "Poliwrath",
            Species::Abra => "Abra",
            Species::Kadabra => "Kadabra",
            Species::Alakazam => "Alakazam",
            Species::Machop => "Machop",
            Species::Machoke => "Machoke",
            Species::Machamp => "Machamp",
            Species::Bellsprout => "Bellsprout",
            Species::Weepinbell => "Weepinbell",
            Species::Victreebel => "Victreebel",
            Species::Tentacool => "Tentacool",
            Species::Tentacruel => "Tentacruel",
            Species::Geodude => "Geodude",
            Species::Graveler => "Graveler",
            Species::Golem => "Golem",
            Species::Ponyta => "Ponyta",
            Species::Rapidash => "Rapidash",
            Species::Slowpoke => "Slowpoke",
            Species::Slowbro => "Slowbro",
            Species::Magnemite => "Magnemite",
            Species::Magneton => "Magneton",
            Species::Farfetchd => "Farfetch'd",
            Species::Doduo => "Doduo",
            Species::Dodrio => "Dodrio",
            Species::Seel => "Seel",
            Species::Dewgong => "Dewgong",
            Species::Grimer => "Grimer",
            Species::Muk => "Muk",
            Species::Shellder => "Shellder",
            Species::Cloyster => "Cloyster",
            Species::Gastly => "Gastly",
            Species::Haunter => "Haunter",
            Species::Gengar => "Gengar",
            Species::Onix => "Onix",
            Species::Drowzee => "Drowzee",
            Species::Hypno => "Hypno",
            Species::Krabby => "Krabby",
            Species::Kingler => "Kingler",
            Species::Voltorb => "Voltorb",
            Species::Electrode => "Electrode",
            Species::Exeggcute => "Exeggcute",
            Species::Exeggutor => "Exeggutor",
            Species::Cubone => "Cubone",
            Species::Marowak => "Marowak",
            Species::Hitmonlee => "Hitmonlee",
            Species::Hitmonchan => "Hitmonchan",
            Species::Lickitung => "Lickitung",
            Species::Koffing => "Koffing",
            Species::Weezing => "Weezing",
            Species::Rhyhorn => "Rhyhorn",
            Species::Rhydon => "Rhydon",
            Species::Chansey => "Chansey",
            Species::Tangela => "Tangela",
            Species::Kangaskhan => "Kangaskhan",
            Species::Horsea => "Horsea",
            Species::Seadra => "Seadra",
            Species::Goldeen => "Goldeen",
            Species::Seaking => "Seaking",
            Species::Staryu => "Staryu",
            Species::Starmie => "Starmie",
            Species::MrMime => "Mr. Mime",
            Species::Scyther => "Scyther",
            Species::Jynx => "Jynx",
            Species::Electabuzz => "Electabuzz",
            Species::Magmar => "Magmar",
            Species::Pinsir => "Pinsir",
            Species::Tauros => "Tauros",
            Species::Magikarp => "Magikarp",
            Species::Gyarados => "Gyarados",
            Species::Lapras => "Lapras",
            Species::Ditto => "Ditto",
            Species::Eevee => "Eevee",
            Species::Vaporeon => "Vaporeon",
            Species::Jolteon => "Jolteon",
            Species::Flareon => "Flareon",
            Species::Porygon => "Porygon",
            Species::Omanyte => "Omanyte",
            Species::Omastar => "Omastar",
            Species::Kabuto => "Kabuto",
            Species::Kabutops => "Kabutops",
            Species::Aerodactyl => "Aerodactyl",
            Species::Snorlax => "Snorlax",
            Species::Articuno => "Articuno",
            Species::Zapdos => "Zapdos",
            Species::Moltres => "Moltres",
            Species::Dratini => "Dratini",
            Species::Dragonair => "Dragonair",
            Species::Dragonite => "Dragonite",
            Species::Mewtwo => "Mewtwo",
            Species::Mew => "Mew",
        }
    }
}

impl fmt::Display for Species {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.name())
    }
}

// Helper function to parse Species enum from filename
impl std::str::FromStr for Species {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let normalized = s.to_lowercase().replace(['-', '_', ' ', '♀', '♂'], "");

        match normalized.as_str() {
            "bulbasaur" => Ok(Species::Bulbasaur),
            "ivysaur" => Ok(Species::Ivysaur),
            "venusaur" => Ok(Species::Venusaur),
            "charmander" => Ok(Species::Charmander),
            "charmeleon" => Ok(Species::Charmeleon),
            "charizard" => Ok(Species::Charizard),
            "squirtle" => Ok(Species::Squirtle),
            "wartortle" => Ok(Species::Wartortle),
            "blastoise" => Ok(Species::Blastoise),
            "caterpie" => Ok(Species::Caterpie),
            "metapod" => Ok(Species::Metapod),
            "butterfree" => Ok(Species::Butterfree),
            "weedle" => Ok(Species::Weedle),
            "kakuna" => Ok(Species::Kakuna),
            "beedrill" => Ok(Species::Beedrill),
            "pidgey" => Ok(Species::Pidgey),
            "pidgeotto" => Ok(Species::Pidgeotto),
            "pidgeot" => Ok(Species::Pidgeot),
            "rattata" => Ok(Species::Rattata),
            "raticate" => Ok(Species::Raticate),
            "spearow" => Ok(Species::Spearow),
            "fearow" => Ok(Species::Fearow),
            "ekans" => Ok(Species::Ekans),
            "arbok" => Ok(Species::Arbok),
            "pikachu" => Ok(Species::Pikachu),
            "raichu" => Ok(Species::Raichu),
            "sandshrew" => Ok(Species::Sandshrew),
            "sandslash" => Ok(Species::Sandslash),
            "nidoranf" | "nidoranfemale" => Ok(Species::NidoranFemale),
            "nidorina" => Ok(Species::Nidorina),
            "nidoqueen" => Ok(Species::Nidoqueen),
            "nidoranm" | "nidoranmale" => Ok(Species::NidoranMale),
            "nidorino" => Ok(Species::Nidorino),
            "nidoking" => Ok(Species::Nidoking),
            "clefairy" => Ok(Species::Clefairy),
            "clefable" => Ok(Species::Clefable),
            "vulpix" => Ok(Species::Vulpix),
            "ninetales" => Ok(Species::Ninetales),
            "jigglypuff" => Ok(Species::Jigglypuff),
            "wigglytuff" => Ok(Species::Wigglytuff),
            "zubat" => Ok(Species::Zubat),
            "golbat" => Ok(Species::Golbat),
            "oddish" => Ok(Species::Oddish),
            "gloom" => Ok(Species::Gloom),
            "vileplume" => Ok(Species::Vileplume),
            "paras" => Ok(Species::Paras),
            "parasect" => Ok(Species::Parasect),
            "venonat" => Ok(Species::Venonat),
            "venomoth" => Ok(Species::Venomoth),
            "diglett" => Ok(Species::Diglett),
            "dugtrio" => Ok(Species::Dugtrio),
            "meowth" => Ok(Species::Meowth),
            "persian" => Ok(Species::Persian),
            "psyduck" => Ok(Species::Psyduck),
            "golduck" => Ok(Species::Golduck),
            "mankey" => Ok(Species::Mankey),
            "primeape" => Ok(Species::Primeape),
            "growlithe" => Ok(Species::Growlithe),
            "arcanine" => Ok(Species::Arcanine),
            "poliwag" => Ok(Species::Poliwag),
            "poliwhirl" => Ok(Species::Poliwhirl),
            "poliwrath" => Ok(Species::Poliwrath),
            "abra" => Ok(Species::Abra),
            "kadabra" => Ok(Species::Kadabra),
            "alakazam" => Ok(Species::Alakazam),
            "machop" => Ok(Species::Machop),
            "machoke" => Ok(Species::Machoke),
            "machamp" => Ok(Species::Machamp),
            "bellsprout" => Ok(Species::Bellsprout),
            "weepinbell" => Ok(Species::Weepinbell),
            "victreebel" => Ok(Species::Victreebel),
            "tentacool" => Ok(Species::Tentacool),
            "tentacruel" => Ok(Species::Tentacruel),
            "geodude" => Ok(Species::Geodude),
            "graveler" => Ok(Species::Graveler),
            "golem" => Ok(Species::Golem),
            "ponyta" => Ok(Species::Ponyta),
            "rapidash" => Ok(Species::Rapidash),
            "slowpoke" => Ok(Species::Slowpoke),
            "slowbro" => Ok(Species::Slowbro),
            "magnemite" => Ok(Species::Magnemite),
            "magneton" => Ok(Species::Magneton),
            "farfetchd" => Ok(Species::Farfetchd),
            "doduo" => Ok(Species::Doduo),
            "dodrio" => Ok(Species::Dodrio),
            "seel" => Ok(Species::Seel),
            "dewgong" => Ok(Species::Dewgong),
            "grimer" => Ok(Species::Grimer),
            "muk" => Ok(Species::Muk),
            "shellder" => Ok(Species::Shellder),
            "cloyster" => Ok(Species::Cloyster),
            "gastly" => Ok(Species::Gastly),
            "haunter" => Ok(Species::Haunter),
            "gengar" => Ok(Species::Gengar),
            "onix" => Ok(Species::Onix),
            "drowzee" => Ok(Species::Drowzee),
            "hypno" => Ok(Species::Hypno),
            "krabby" => Ok(Species::Krabby),
            "kingler" => Ok(Species::Kingler),
            "voltorb" => Ok(Species::Voltorb),
            "electrode" => Ok(Species::Electrode),
            "exeggcute" => Ok(Species::Exeggcute),
            "exeggutor" => Ok(Species::Exeggutor),
            "cubone" => Ok(Species::Cubone),
            "marowak" => Ok(Species::Marowak),
            "hitmonlee" => Ok(Species::Hitmonlee),
            "hitmonchan" => Ok(Species::Hitmonchan),
            "lickitung" => Ok(Species::Lickitung),
            "koffing" => Ok(Species::Koffing),
            "weezing" => Ok(Species::Weezing),
            "rhyhorn" => Ok(Species::Rhyhorn),
            "rhydon" => Ok(Species::Rhydon),
            "chansey" => Ok(Species::Chansey),
            "tangela" => Ok(Species::Tangela),
            "kangaskhan" => Ok(Species::Kangaskhan),
            "horsea" => Ok(Species::Horsea),
            "seadra" => Ok(Species::Seadra),
            "goldeen" => Ok(Species::Goldeen),
            "seaking" => Ok(Species::Seaking),
            "staryu" => Ok(Species::Staryu),
            "starmie" => Ok(Species::Starmie),
            "mrmime" => Ok(Species::MrMime),
            "scyther" => Ok(Species::Scyther),
            "jynx" => Ok(Species::Jynx),
            "electabuzz" => Ok(Species::Electabuzz),
            "magmar" => Ok(Species::Magmar),
            "pinsir" => Ok(Species::Pinsir),
            "tauros" => Ok(Species::Tauros),
            "magikarp" => Ok(Species::Magikarp),
            "gyarados" => Ok(Species::Gyarados),
            "lapras" => Ok(Species::Lapras),
            "ditto" => Ok(Species::Ditto),
            "eevee" => Ok(Species::Eevee),
            "vaporeon" => Ok(Species::Vaporeon),
            "jolteon" => Ok(Species::Jolteon),
            "flareon" => Ok(Species::Flareon),
            "porygon" => Ok(Species::Porygon),
            "omanyte" => Ok(Species::Omanyte),
            "omastar" => Ok(Species::Omastar),
            "kabuto" => Ok(Species::Kabuto),
            "kabutops" => Ok(Species::Kabutops),
            "aerodactyl" => Ok(Species::Aerodactyl),
            "snorlax" => Ok(Species::Snorlax),
            "articuno" => Ok(Species::Articuno),
            "zapdos" => Ok(Species::Zapdos),
            "moltres" => Ok(Species::Moltres),
            "dratini" => Ok(Species::Dratini),
            "dragonair" => Ok(Species::Dragonair),
            "dragonite" => Ok(Species::Dragonite),
            "mewtwo" => Ok(Species::Mewtwo),
            "mew" => Ok(Species::Mew),
            _ => Err(format!("Unknown species: {}", s)),
        }
    }
}
