// In: src/move_data.rs

use crate::errors::{MoveDataError, MoveDataResult};
use schema::{Move, MoveData};

// This line includes the functions generated by `build.rs` (e.g., get_compiled_move_data).
include!(concat!(env!("OUT_DIR"), "/generated_data.rs"));

/// Get move data for a specific move. This is the public data access function.
pub fn get_move_data(move_: Move) -> MoveDataResult<MoveData> {
    get_compiled_move_data()
        .get(&move_)
        .cloned()
        .ok_or(MoveDataError::MoveNotFound(move_))
}

/// Get the max PP for a specific move.
pub fn get_move_max_pp(move_: Move) -> MoveDataResult<u8> {
    // This logic is sound and remains unchanged.
    get_move_data(move_).map(|data| data.max_pp)
}
